# Generated by Django 2.2.5 on 2019-10-02 06:32

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('category', models.CharField(choices=[('C', 'Casual'), ('F', 'Formal'), ('S', 'Sports'), ('K', 'Kids')], max_length=1)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('discription', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to=products.models.upload_image_path)),
            ],
        ),
    ]
